spring.application.name=ProductCrud

#setting sql connection
spring.datasource.url = jdbc:mysql://192.168.10.117:3306/dac35?useSSL=false
spring.datasource.username=dac35
spring.datasource.password=welcome

#setting hibenate properties
spring.jpa.properties.hibernate.dailect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jap.properties.hibernate.format_sql=true